export type Company = {
  id: string;
  name: string;
  initials: string;
  industry: string;
  companyType?: string;
  location: string;
  size: string;
  website: string;
  linkedin: string;
  description: string;
  founded: number;
  peopleCount: number;
  relevanceScore?: number;
};

export type Lead = {
  id: string;
  name: string;
  initials: string;
  role: string;
  title: string;
  companyId: string;
  companyName: string;
  industry: string;
  location: string;
  email: string;
  website: string;
  linkedin: string;
  seniority: string;
  department: string;
  score: number;
  saved: boolean;
};

export type SearchFilters = {
  industry: any;
  location: string;
  companySize: string;
  title: any;
};

export type SearchRecord = {
  id: string;
  query: string;
  filters: SearchFilters;
  createdAt: string;
  resultCount: number;
};

export const industries = [
  "Accounting",
  "Airlines & Aviation",
  "Alternative Dispute Resolution",
  "Alternative Medicine",
  "Animation",
  "Apparel & Fashion",
  "Architecture & Planning",
  "Arts & Crafts",
  "Automotive",
  "Aviation & Aerospace",
  "Banking",
  "Biotechnology",
  "Broadcast Media",
  "Building Materials",
  "Business Supplies & Equipment",
  "Capital Markets",
  "Chemicals",
  "Civic & Social Organization",
  "Civil Engineering",
  "Commercial Real Estate",
  "Computer & Network Security",
  "Computer Games",
  "Computer Hardware",
  "Computer Networking",
  "Computer Software",
  "Construction",
  "Consumer Goods",
  "Consumer Services",
  "Cosmetics",
  "Dairy",
  "Defense & Space",
  "Design",
  "E-commerce",
  "Education",
  "Electrical & Electronic Manufacturing",
  "Entertainment",
  "Environmental Services",
  "Events Services",
  "Executive Office",
  "Facilities Services",
  "Farming",
  "Financial Services",
  "Fine Art",
  "Fishery",
  "Food & Beverage",
  "Food Production",
  "Fundraising",
  "Furniture",
  "Gambling & Casinos",
  "Glass, Ceramics & Concrete",
  "Government Administration",
  "Government Relations",
  "Graphic Design",
  "Health, Wellness & Fitness",
  "Healthcare",
  "Higher Education",
  "Hospitality",
  "Human Resources",
  "Import & Export",
  "Individual & Family Services",
  "Industrial Automation",
  "Information Technology & Services",
  "Insurance",
  "International Affairs",
  "International Trade & Development",
  "Internet",
  "Investment Banking",
  "Investment Management",
  "Legal Services",
  "Leisure, Travel & Tourism",
  "Logistics & Supply Chain",
  "Luxury Goods & Jewelry",
  "Machinery",
  "Management Consulting",
  "Maritime",
  "Market Research",
  "Marketing & Advertising",
  "Mechanical & Industrial Engineering",
  "Media Production",
  "Medical Devices",
  "Medical Practice",
  "Mental Health Care",
  "Mining & Metals",
  "Motion Pictures & Film",
  "Museums & Institutions",
  "Music",
  "Nanotechnology",
  "Newspapers",
  "Nonprofit Organization Management",
  "Oil & Energy",
  "Online Media",
  "Outsourcing & Offshoring",
  "Packaging & Containers",
  "Paper & Forest Products",
  "Performing Arts",
  "Pharmaceuticals",
  "Photography",
  "Plastics",
  "Political Organization",
  "Primary & Secondary Education",
  "Printing",
  "Professional Training & Coaching",
  "Program Development",
  "Public Policy",
  "Public Relations & Communications",
  "Public Safety",
  "Publishing",
  "Railroad Manufacture",
  "Real Estate",
  "Recreational Facilities & Services",
  "Religious Institutions",
  "Renewables & Environment",
  "Research",
  "Restaurants",
  "Retail",
  "Security & Investigations",
  "Semiconductors",
  "Shipbuilding",
  "Sporting Goods",
  "Sports",
  "Staffing & Recruiting",
  "Supermarkets",
  "Telecommunications",
  "Textiles",
  "Think Tanks",
  "Tobacco",
  "Translation & Localization",
  "Transportation",
  "Utilities",
  "Venture Capital & Private Equity",
  "Veterinary",
  "Warehousing",
  "Wholesale",
  "Wine & Spirits",
  "Wireless",
  "Writing & Editing",
];
export const locations = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Argentina",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Belgium",
  "Brazil",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Egypt",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Latvia",
  "Lebanon",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Maldives",
  "Malta",
  "Mauritius",
  "Mexico",
  "Monaco",
  "Morocco",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Panama",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saudi Arabia",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Zambia",
  "Zimbabwe",
  "Lahore, Pakistan",
  "Karachi, Pakistan",
  "Islamabad, Pakistan",
  "Rawalpindi, Pakistan",
  "Faisalabad, Pakistan",
  "Multan, Pakistan",
  "Peshawar, Pakistan",
  "Quetta, Pakistan",
  "Sialkot, Pakistan",
  "Punjab, Pakistan",
  "Sindh, Pakistan",
  "Khyber Pakhtunkhwa, Pakistan",
  "California, United States",
  "New York, United States",
  "Texas, United States",
  "Florida, United States",
  "Ontario, Canada",
  "British Columbia, Canada",
  "New South Wales, Australia",
  "Victoria, Australia",
  "England, United Kingdom",
  "Scotland, United Kingdom",
  "Dubai, United Arab Emirates",
  "Abu Dhabi, United Arab Emirates",
  "London, United Kingdom",
  "Manchester, United Kingdom",
  "New York City, United States",
  "Los Angeles, United States",
  "San Francisco, United States",
  "Chicago, United States",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Singapore",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Berlin, Germany",
  "Munich, Germany",
  "Paris, France",
  "Lyon, France",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Milan, Italy",
  "Rome, Italy",
  "Amsterdam, Netherlands",
  "Zurich, Switzerland",
  "Istanbul, Turkey",
  "Cairo, Egypt",
  "Nairobi, Kenya",
  "Lagos, Nigeria",
  "Johannesburg, South Africa",
  "Cape Town, South Africa",
  "Mumbai, India",
  "Delhi, India",
  "Bengaluru, India",
  "Hyderabad, India",
  "Dhaka, Bangladesh",
  "Colombo, Sri Lanka",
  "Kuala Lumpur, Malaysia",
  "Bangkok, Thailand",
  "Jakarta, Indonesia",
  "Manila, Philippines",
  "Seoul, South Korea",
  "Beijing, China",
  "Shanghai, China",
];
export const titles = [
  "Account Executive",
  "Account Manager",
  "Accountant",
  "Administrative Assistant",
  "Anchor",
  "Anchor Reporter",
  "Art Director",
  "Assistant Controller",
  "Brand Manager",
  "Business Analyst",
  "Business Development Manager",
  "Business Development Representative",
  "CEO",
  "CFO",
  "CGO",
  "CHRO",
  "CIO",
  "CISO",
  "CLO",
  "CMO",
  "COO",
  "CPO",
  "CRO",
  "CTO",
  "Chief Executive Officer",
  "Chief Financial Officer",
  "Chief Human Resources Officer",
  "Chief Information Officer",
  "Chief Marketing Officer",
  "Chief Operating Officer",
  "Chief Product Officer",
  "Chief Revenue Officer",
  "Chief Technology Officer",
  "Community Manager",
  "Content Manager",
  "Content Strategist",
  "Controller",
  "Copywriter",
  "Customer Experience Manager",
  "Customer Success Manager",
  "Customer Success Specialist",
  "Customer Support Manager",
  "Customer Support Specialist",
  "Data Analyst",
  "Data Engineer",
  "Data Scientist",
  "Database Administrator",
  "Design Director",
  "Designer",
  "DevOps Engineer",
  "Digital Marketing Manager",
  "Director of Business Development",
  "Director of Customer Success",
  "Director of Engineering",
  "Director of Finance",
  "Director of Human Resources",
  "Director of Information Technology",
  "Director of Marketing",
  "Director of Operations",
  "Director of Partnerships",
  "Director of Product",
  "Director of Sales",
  "E-commerce Manager",
  "Editor",
  "Electrical Engineer",
  "Email Marketing Manager",
  "Engineering Manager",
  "Enterprise Account Executive",
  "Executive Assistant",
  "Finance Manager",
  "Financial Analyst",
  "Founder",
  "Frontend Developer",
  "General Manager",
  "Graphic Designer",
  "Growth Hacker",
  "Growth Manager",
  "Head of Business Development",
  "Head of Customer Success",
  "Head of Engineering",
  "Head of Finance",
  "Head of Growth",
  "Head of Information Technology",
  "Head of Marketing",
  "Head of Operations",
  "Head of Partnerships",
  "Head of People",
  "Head of Product",
  "Head of Sales",
  "Head of Talent",
  "HR",
  "HR Assistant",
  "HR Business Partner",
  "HR Coordinator",
  "HR Executive",
  "HR Generalist",
  "HR Manager",
  "HR Officer",
  "HR Specialist",
  "Human Resources Assistant",
  "Human Resources Coordinator",
  "Human Resources Executive",
  "Human Resources Generalist",
  "Human Resources Manager",
  "Human Resources Officer",
  "Human Resources Specialist",
  "Inside Sales Representative",
  "Information Technology Manager",
  "IT Director",
  "IT Manager",
  "Key Account Manager",
  "Legal Counsel",
  "Learning and Development Manager",
  "Logistics Manager",
  "Managing Director",
  "Market Research Analyst",
  "Marketing Coordinator",
  "Marketing Director",
  "Marketing Manager",
  "Mechanical Engineer",
  "Merchandising Manager",
  "Office Manager",
  "Operations Analyst",
  "Owner",
  "Business Owner",
  "Company Owner",
  "Operations Manager",
  "Partnerships Manager",
  "People Operations Manager",
  "Performance Marketing Manager",
  "Pharmacy Manager",
  "Photographer",
  "Professional Photographer",
  "Portrait Photographer",
  "Commercial Photographer",
  "Fashion Photographer",
  "Event Photographer",
  "Wedding Photographer",
  "Product Photographer",
  "Sports Photographer",
  "Photojournalist",
  "Photography Assistant",
  "Photography Director",
  "Photography Instructor",
  "Photography Intern",
  "Photography Manager",
  "Senior Photographer",
  "Videographer",
  "Video Photographer",
  "Product Designer",
  "Product Manager",
  "Product Marketing Manager",
  "Product Owner",
  "Program Manager",
  "Project Coordinator",
  "Project Manager",
  "Public Relations Manager",
  "QA Engineer",
  "Quality Assurance Manager",
  "Recruiter",
  "Recruiting Coordinator",
  "Regional Sales Manager",
  "Research Analyst",
  "Revenue Operations Manager",
  "Sales Development Representative",
  "Sales Director",
  "Sales Engineer",
  "Sales Manager",
  "Sales Operations Manager",
  "Sales Representative",
  "SEO Manager",
  "SEO Specialist",
  "Social Media Manager",
  "Software Engineer",
  "Solutions Architect",
  "Sports Marketing Manager",
  "Strategy Manager",
  "Supply Chain Manager",
  "Teacher",
  "Teacher Assistant",
  "Teaching Assistant",
  "Head Teacher",
  "School Teacher",
  "Primary Teacher",
  "Subject Teacher",
  "English Teacher",
  "Math Teacher",
  "Talent Acquisition Manager",
  "Talent Acquisition Specialist",
  "Technical Recruiter",
  "Training Manager",
  "Treasury Manager",
  "UI Designer",
  "UX Designer",
  "UX Researcher",
  "Vice President of Engineering",
  "Vice President of Finance",
  "Vice President of Marketing",
  "Vice President of Operations",
  "Vice President of Product",
  "Vice President of Sales",
  "VP Business Development",
  "VP Customer Success",
  "VP Engineering",
  "VP Finance",
  "VP Growth",
  "VP Marketing",
  "VP Partnerships",
  "VP Product",
  "VP Revenue",
  "VP Sales",
  "Web Developer",
];
export const companySizes = [
  "1–10",
  "11–50",
  "51–200",
  "201–500",
  "1,000–5,000",
  "5,000+",
];
